# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mdrev < Formula
  desc "Review markdown documents — inline comments, questions and suggested edits"
  homepage "https://github.com/esivres/mdrev"
  version "0.1.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/esivres/mdrev/releases/download/v0.1.5/mdrev_0.1.5_darwin_amd64.tar.gz"
      sha256 "3dc6d8868504579868080b381c1bf56ac333f87acd45e5334dc8047d6a053b36"

      define_method(:install) do
        bin.install "mdrev"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/esivres/mdrev/releases/download/v0.1.5/mdrev_0.1.5_darwin_arm64.tar.gz"
      sha256 "5b4c6ecdf5f6cdea64f1b95ea55cffd826e04e381f4d21189f51fc059cbb92a4"

      define_method(:install) do
        bin.install "mdrev"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/esivres/mdrev/releases/download/v0.1.5/mdrev_0.1.5_linux_amd64.tar.gz"
      sha256 "63f5e29beb5417cf104f069f4d0df7d9d3f805689f1a5f76bcaee45240a7aa30"
      define_method(:install) do
        bin.install "mdrev"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/esivres/mdrev/releases/download/v0.1.5/mdrev_0.1.5_linux_arm64.tar.gz"
      sha256 "cdb1ee27cde6eba7cae87f06ba1def160feeaa39e2d788e086bb8f258681f594"
      define_method(:install) do
        bin.install "mdrev"
      end
    end
  end

  test do
    system "#{bin}/mdrev", "--help"
  end
end
