# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mdrev < Formula
  desc "Review markdown documents — inline comments, questions and suggested edits"
  homepage "https://github.com/esivres/mdrev"
  version "0.1.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/esivres/mdrev/releases/download/v0.1.4/mdrev_0.1.4_darwin_amd64.tar.gz"
      sha256 "762d80e1cd5de55fd3baf3ccc264598a6b515b8518420dd58dcc61ec0c51cedf"

      define_method(:install) do
        bin.install "mdrev"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/esivres/mdrev/releases/download/v0.1.4/mdrev_0.1.4_darwin_arm64.tar.gz"
      sha256 "e30c3308997254a44dac39160be61c60d0e2d9f269490732c8d2c45db41ce964"

      define_method(:install) do
        bin.install "mdrev"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/esivres/mdrev/releases/download/v0.1.4/mdrev_0.1.4_linux_amd64.tar.gz"
      sha256 "657a718b7fd8b896b81465d818ccba1f76e65b3fc2fb37a03257cf24ab8ac0dd"
      define_method(:install) do
        bin.install "mdrev"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/esivres/mdrev/releases/download/v0.1.4/mdrev_0.1.4_linux_arm64.tar.gz"
      sha256 "8a283ae62fe5b48c11a2aeea286c13bc497c50c059fd73387fe11ac908f57d07"
      define_method(:install) do
        bin.install "mdrev"
      end
    end
  end

  test do
    system "#{bin}/mdrev", "--help"
  end
end
