# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mdrev < Formula
  desc "Review markdown documents — inline comments, questions and suggested edits"
  homepage "https://github.com/esivres/mdrev"
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/esivres/mdrev/releases/download/v0.1.2/mdrev_0.1.2_darwin_amd64.tar.gz"
      sha256 "f1056b732af81db6a7bb6168a85977011bbc5341655928e919e3a4669d30bcd9"

      define_method(:install) do
        bin.install "mdrev"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/esivres/mdrev/releases/download/v0.1.2/mdrev_0.1.2_darwin_arm64.tar.gz"
      sha256 "a013b25d7c792fdc007b9bd706deaf03154dc985b096cb8aa5ab342efb198417"

      define_method(:install) do
        bin.install "mdrev"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/esivres/mdrev/releases/download/v0.1.2/mdrev_0.1.2_linux_amd64.tar.gz"
      sha256 "51c597298331180dfdc0733833c15fde61e255e6ed395e6831c4c98e71498b92"
      define_method(:install) do
        bin.install "mdrev"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/esivres/mdrev/releases/download/v0.1.2/mdrev_0.1.2_linux_arm64.tar.gz"
      sha256 "b51a13d73742e8b206624f9f1a286d386d2545ef2d11aabc0ccf7624da140e22"
      define_method(:install) do
        bin.install "mdrev"
      end
    end
  end

  test do
    system "#{bin}/mdrev", "--help"
  end
end
